### ISSUE TITLE
Support workflow_dispatch

### ISSUE THREAD

**Issue by henriktelia** [mi-kas/kover-report#174]
It's quite a problem for me that I can't trigger a workflow "by hand" even on a PR. What is the rationale for disallowing this?

**Comment by mi-kas** [comment]
Sorry for the late reply! You can trigger the action however you want and there is no restriction in place for `kover-report`. You could use a workflow_dispatch trigger with something like this:

```yaml
name: Measure coverage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
```
