### ISSUE TITLE
Document permissions for github action?

### ISSUE THREAD

**Issue by WildOrangutan** [mi-kas/kover-report#287]
Maybe document required permissions, for the action to work?

I feel like we can avoid some friction like that, when setting up the action 🙂  

```yml
permissions:          
  contents: read      
  pull-requests: write
```
