### ISSUE TITLE
Support glob format for xml files

### ISSUE THREAD

**Issue by ty1824** [mi-kas/kover-report#96]
I have a multi-module project and would like to publish each individual coverage report without having to manually specify the file. However, if I use a glob format, I get the error:
`Error: ENOENT: no such file or directory, open '**/reports/kover/report.xml'`

Ideally this would work similarly to other test reporting actions (I am currently using [dorny/test-reporter@v1](https://github.com/marketplace/actions/test-reporter), for example).

**Comment by mi-kas** [comment]
@ty1824 Thanks for bringing this up! I will look into making the action compatible with multi-module projects

**Comment by ty1824** [comment]
Thanks for providing this action and the quick response 😊

**Comment by ty1824** [comment]
Realized I never left an example. My pull request build action: https://github.com/ty1824/dialector/blob/main/.github/workflows/pull-request-build.yml

**Comment by mi-kas** [comment]
@ty1824 With v1.7 support for multi-module project got introduced. Basically you can pass now multiple report files to the action like this: 

```yaml
        ...
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/project1/build/reports/kover/report.xml
            ${{ github.workspace }}/project2/build/reports/kover/report.xml
```

 Does this resolve your problem?
